name: Azure Naming Tool - Build and deploy to an Azure Web App
env:
  DOTNET_VERSION: '8.0.x'
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
permissions:
  contents: read
  id-token: write # This is required for requesting the JWT token
                  
jobs:
  check-secrets:
    runs-on: ubuntu-latest
    outputs:
      secrets-valid: ${{ steps.secrets-valid.outputs.isvalid }}
    steps:
      - uses: actions/checkout@v3      
      - id: secrets-valid
        env: 
          azure_webapp_name: ${{ secrets.AZURE_WEBAPP_NAME }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        # Client secret no longer needed with federated credentials
        if: (env.azure_webapp_name != null && env.azure_client_id != null && env.azure_subscription_id != null && env.azure_tenant_id != null)
        run: echo 'isvalid=true' >> $GITHUB_OUTPUT
          
  build:
    runs-on: ubuntu-latest
    needs: [check-secrets]
    if: needs.check-secrets.outputs.secrets-valid == 'true'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: Build with dotnet
        run: dotnet build src --configuration Release
      
      - name: dotnet publish
        run: dotnet publish src -c Release -o ${{github.workspace}}/publish
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4.4.3
        with:
          name: .net-app
          path: ${{github.workspace}}/publish
  
  deploy: 
    permissions:
      contents: read
      id-token: write # Needed for OIDC authentication
    runs-on: ubuntu-latest
    needs: [build, check-secrets]
    if: needs.check-secrets.outputs.secrets-valid == 'true'
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4.1.8
        with:
          name: .net-app
          path: ${{github.workspace}}/publish
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # Removed client-secret as we're using federated credentials
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: ${{github.workspace}}/publish
